spring:
  datasource:
    url: jdbc:h2:file:/tmp/db;MODE=MySQL;AUTO_SERVER=TRUE;INIT=CREATE SCHEMA IF NOT EXISTS CLIENTE
    username: cliente
    password: cliente
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: create
      naming:
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        generate_statistics: false
